/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IItem } from "./types/item.interface";
export namespace Components {
    interface MyComponent {
        "item": IItem;
        "showLinks": boolean;
    }
    interface MyComponentLink {
        "item": IItem;
    }
    interface MyRoot {
        "showLinks": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyComponentLinkElement extends Components.MyComponentLink, HTMLStencilElement {
    }
    var HTMLMyComponentLinkElement: {
        prototype: HTMLMyComponentLinkElement;
        new (): HTMLMyComponentLinkElement;
    };
    interface HTMLMyRootElement extends Components.MyRoot, HTMLStencilElement {
    }
    var HTMLMyRootElement: {
        prototype: HTMLMyRootElement;
        new (): HTMLMyRootElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-component-link": HTMLMyComponentLinkElement;
        "my-root": HTMLMyRootElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "item"?: IItem;
        "showLinks"?: boolean;
    }
    interface MyComponentLink {
        "item"?: IItem;
    }
    interface MyRoot {
        "showLinks"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-component-link": MyComponentLink;
        "my-root": MyRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-component-link": LocalJSX.MyComponentLink & JSXBase.HTMLAttributes<HTMLMyComponentLinkElement>;
            "my-root": LocalJSX.MyRoot & JSXBase.HTMLAttributes<HTMLMyRootElement>;
        }
    }
}
